import type { Metadata } from "next";
import { Lato, Geist_Mono, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const Lexend_DecaSans = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${Lexend_DecaSans.variable} ${geistMono.variable} antialiased`} 
      >
        {children}
      </body>
    </html>
  );
}
